EXP_NAME: "4096_1028_random_zarr_cosine_scheduler"
DEBUG_MODE: false
DATASET:
  MODE: 'zarr' 
  CROP_SIZE: 4096
  IMG_SIZE: 1024
PREPAIRED:
  CROP_PATH: "../input/train_v3_4096_1024"
TRAIN:
  EPOCH: 60
  ITERATIONS_PER_EPOCH: 50

OPTIMIZER:
  NAME: "torch.optim.Adam"
  CFG:
    lr: 0.0001
  SCHEDULER:
    NAME: "src.schedulers.warmup_scheduler.GradualWarmupSchedulerV2"
    CFG:
      multiplier: 10
      total_epoch: 1
      cosine_epo: 50