EXP_NAME: "1024_512_two_head_dice_pos"
FOLD: 0
DEBUG_MODE: false
DATASET:
  MODE: 'zarr_prepaired' 
  CROP_SIZE: 1024
  IMG_SIZE: 512
  STEP: 1024
PREPAIRED:
  CROP_PATH: "../input/train_v3_4096_1024"
  BATCH_TARGET_WEIGHTS: [0.5, 0.5]
TRAIN:
  EPOCH: 50
  ITERATIONS_PER_EPOCH: 50
  BATCH_SIZE: 64
  NUM_WORKERS: 30
VAL:
  BATCH_SIZE: 64

OPTIMIZER:
  NAME: "torch.optim.Adam"
  CFG:
    lr: 0.001
  SCHEDULER:
    NAME: "torch.optim.lr_scheduler.ReduceLROnPlateau"
    CFG:
      mode: "max"
      patience: 4
      factor: 0.5
      verbose: true

MODEL:
    CFG:
      encoder_name: "resnet34"
      encoder_weights: "imagenet"
      aux_params: 
        classes: 1
        activation: null

# LOSS_FN: 
#   NAME: "src.losses.losses.MyLoss"

KEY_METRIC: "dice_pos"